// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk2OTIQt2dL2o31BQHLxf2RR7HJhGnpCk',
    appId: '1:1083001724485:web:671aad7842d5edd01fcd2c',
    messagingSenderId: '1083001724485',
    projectId: 'notes-ce9f5',
    authDomain: 'notes-ce9f5.firebaseapp.com',
    storageBucket: 'notes-ce9f5.firebasestorage.app',
    measurementId: 'G-847RFP38Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6IXl4--T2Bib8twqTkSEXKngjGCNs5go',
    appId: '1:1083001724485:android:a9474d1f606761b01fcd2c',
    messagingSenderId: '1083001724485',
    projectId: 'notes-ce9f5',
    storageBucket: 'notes-ce9f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8YUhD83Elb9AJRZF7Dz0w946q66YsNsQ',
    appId: '1:1083001724485:ios:e6fcbc003b4315aa1fcd2c',
    messagingSenderId: '1083001724485',
    projectId: 'notes-ce9f5',
    storageBucket: 'notes-ce9f5.firebasestorage.app',
    iosBundleId: 'com.example.task7FlutterfireNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8YUhD83Elb9AJRZF7Dz0w946q66YsNsQ',
    appId: '1:1083001724485:ios:e6fcbc003b4315aa1fcd2c',
    messagingSenderId: '1083001724485',
    projectId: 'notes-ce9f5',
    storageBucket: 'notes-ce9f5.firebasestorage.app',
    iosBundleId: 'com.example.task7FlutterfireNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk2OTIQt2dL2o31BQHLxf2RR7HJhGnpCk',
    appId: '1:1083001724485:web:f19e6abafd2f0e621fcd2c',
    messagingSenderId: '1083001724485',
    projectId: 'notes-ce9f5',
    authDomain: 'notes-ce9f5.firebaseapp.com',
    storageBucket: 'notes-ce9f5.firebasestorage.app',
    measurementId: 'G-YL2F74K2C7',
  );
}
